const { GoogleGenAI } = require("@google/genai")
const puppeteer = require("puppeteer")
const { z } = require("zod")
const ai = new GoogleGenAI({
    apiKey: process.env.GOOGLE_GENAI_API_KEY
})




async function callWithRetry(fn, retries = 3) {
    for (let attempt = 1; attempt <= retries; attempt++) {
        try {
            return await fn();
        } catch (err) {
            const is429 = err?.status === 429 || err?.message?.includes("429") || err?.message?.includes("RESOURCE_EXHAUSTED");
            const is503 = err?.status === 503 || err?.message?.toLowerCase().includes("unavailable") || err?.message?.toLowerCase().includes("high demand");
            if ((is429 || is503) && attempt < retries) {
                // Parse retryDelay from error message e.g. "Please retry in 18.9s"
                const match = err.message?.match(/retry in (\d+(\.\d+)?)/i);
                const waitMs = match ? Math.ceil(parseFloat(match[1])) * 1000 : 20000;
                console.log(`Rate limited/unavailable. Retrying in ${waitMs / 1000}s (attempt ${attempt}/${retries})...`);
                await new Promise(r => setTimeout(r, waitMs));
            } else {
                throw err;
            }
        }
    }
}

async function generateInterviewReport({ resume, resumeBuffer, resumeMimeType, selfDescription, jobDescription }) {

    const promptText = `You are an expert interview coach and career advisor. Analyze the following candidate profile and job description, then generate a comprehensive interview preparation report.

${resume ? `CANDIDATE RESUME:\n${resume}\n` : `(A candidate resume document is attached to this prompt.)\n`}
CANDIDATE SELF-DESCRIPTION:
${selfDescription}

JOB DESCRIPTION:
${jobDescription}

Generate a detailed JSON report with ALL of the following fields filled out completely. Do NOT leave any array empty.

Return ONLY a valid JSON object with this EXACT structure:
{
  "title": "<job title from job description>",
  "matchScore": <number 0-100 indicating how well the candidate matches the job>,
  "technicalQuestions": [
    {
      "question": "<specific technical question based on job requirements and candidate background>",
      "intention": "<why an interviewer would ask this question>",
      "answer": "<detailed guide on how to answer this question with key points to cover>"
    }
  ],
  "behavioralQuestions": [
    {
      "question": "<behavioral question using STAR method topics>",
      "intention": "<why an interviewer would ask this question>",
      "answer": "<how to structure and answer this using the STAR method with specific examples>"
    }
  ],
  "skillGaps": [
    {
      "skill": "<skill the candidate is missing or weak in based on job requirements>",
      "severity": "<low|medium|high>"
    }
  ],
  "preparationPlan": [
    {
      "day": <day number starting from 1>,
      "focus": "<main topic to focus on this day>",
      "tasks": ["<specific task 1>", "<specific task 2>", "<specific task 3>"]
    }
  ],
  "atsScore": <number 0-100 indicating ATS friendliness of the resume>,
  title:z.string().describe("title of the interview report")
}

REQUIREMENTS:
- technicalQuestions: generate at least 5 questions specific to the job requirements
- behavioralQuestions: generate at least 3 questions
- skillGaps: identify at least 2-3 gaps comparing resume to job requirements  
- preparationPlan: create a 7-day preparation plan
- matchScore: be honest and precise based on skill alignment
- All answers must be detailed and actionable, not generic

Return ONLY the JSON, no markdown, no explanation.
the content should be in the resume not sound like generated by ai and should be close to possible to the human written resume
the overall design should be simple and professional
the content should be ATS friendly, i.e. use simple fonts and layout, avoid tables and columns
the resume should be not so lengthy, it should be 1-2 pages when converted to pdf. focus on quality over quantity and make sure to add all relevant information that can increase the chances of getting selected or getting a call for an interview`

    let requestContents = promptText;
    
    if (resumeBuffer && resumeMimeType) {
        requestContents = [
            {
                inlineData: {
                    data: resumeBuffer.toString("base64"),
                    mimeType: resumeMimeType
                }
            },
            { text: promptText }
        ];
    }

    const response = await callWithRetry(() => ai.models.generateContent({
        model: "gemini-3-flash-preview",
        contents: requestContents,
        config: {
            responseMimeType: "application/json",
        }
    }));

    const text = response.text;
    if (!text) throw new Error("Empty response from Gemini AI");
    return JSON.parse(text);
}

async function generatePdfFromHtml(htmlContent){
    
    const browser = await puppeteer.launch({
        headless: true,
        args: ['--no-sandbox', '--disable-setuid-sandbox']
    });
    const page = await browser.newPage();
    await page.setContent(htmlContent);
    const pdf = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: { top: '1cm', right: '1cm', bottom: '1cm', left: '1cm' }
    });
    await browser.close();
    return pdf;
}

async function generateResumePDF(resume,selfDescription,jobDescription){
    
  const resumepdfSchema = z.object({ 
    html: z.string().describe("the html content of the resume which can be converted to pdf using puppeteer") 
  })

  const promptText = `Generate a resume in HTML format based on the following information:

${resume ? `CANDIDATE RESUME:\n${resume}\n` : `(A candidate resume document is attached to this prompt.)\n`}
CANDIDATE SELF-DESCRIPTION:
${selfDescription}

JOB DESCRIPTION:
${jobDescription}

the responce should be in the JSON object with the single field "html" and the value should be the html content of the resume.

Return ONLY the JSON, no markdown, no explanation.`

const response = await callWithRetry(() => ai.models.generateContent({
    model: "gemini-3-flash-preview",
    contents: promptText,
    config: {
        responseMimeType: "application/json",
    }
}));

const text = response.text;
if (!text) throw new Error("Empty response from Gemini AI");
const jsonContent =JSON.parse(text);
const pdfBuffer = await generatePdfFromHtml(jsonContent.html);
return pdfBuffer;

}

module.exports = { generateInterviewReport, generateResumePDF}

// async function generateContent(prompt) {
//     const result = await model.generateContent(prompt);
//     const response = await result.response;
//     const text = response.text();
//     return text;
// }